DROP TABLE IF EXISTS users, categories, events, compilations, compilation_events, locations, comments CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    email varchar(254)                         NOT NULL UNIQUE,
    name  varchar(250)                         NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name varchar(50)                          NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY UNIQUE,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY               NOT NULL PRIMARY KEY,
    annotation         varchar(2000)                                      NOT NULL,
    category_id        BIGINT REFERENCES categories (id) ON DELETE NO ACTION NOT NULL,
    description        varchar(7000)                                      NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE                        NOT NULL,
    location_id        BIGINT                                             NOT NULL REFERENCES locations (id),
    paid               boolean                                            NOT NULL DEFAULT false,
    participant_limit  BIGINT                                                NOT NULL DEFAULT 0,
    request_moderation boolean                                            NOT NULL DEFAULT true,
    title              varchar(120)                                       NOT NULL,
    initiator_id       BIGINT                                                NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    state              varchar(255)                                       NOT NULL DEFAULT 'PENDING',
    created_on         TIMESTAMP WITHOUT TIME ZONE                        NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    pinned boolean                              NOT NULL DEFAULT false,
    title  varchar(50)                          NOT NULL
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    event_id     BIGINT                                         NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    requester_id BIGINT                                         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status       varchar(255)                                NOT NULL DEFAULT 'PENDING',
    created_date TIMESTAMP WITHOUT TIME ZONE                 NOT NULL,
    CONSTRAINT requests_pk PRIMARY KEY (requester_id, event_id)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT REFERENCES compilations (id) ON DELETE CASCADE NOT NULL,
    event_id       BIGINT REFERENCES events (id) ON DELETE CASCADE       NOT NULL,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    text         varchar(2000)                        NOT NULL,
    author_id    BIGINT                                  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    event_id     BIGINT                                  NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    created_date TIMESTAMP WITHOUT TIME ZONE          NOT NULL
);